REGULAR_ACCOUNT = ''
REGULAR_USERNAME = ''
REGULAR_PASSWORD = ''

PAPER_ACCOUNT = 'DU1892654'
PAPER_USERNAME = 'amir3740'
PAPER_PASSWORD = 'testTest1'

# PAPER_ACCOUNT = 'DU1745169'
# PAPER_USERNAME = 'thburk797'
# PAPER_PASSWORD = 'Te8286rSMVbRbUAn'

# PAPER_ACCOUNT = ''
# PAPER_USERNAME = ''
# PAPER_PASSWORD = ''

MAX_DOWN = 0.2 # percent
TRAILING_PERC = 0.2 # percent
